config/routes.rb
Showtrac::Application.routes.draw do
  
  
  resources :services

  resources :statuses

  resources :pregnancies do
    resources :matings
    resources :litters
  end

  resources :colors

  resources :photos

  resources :payment_statuses

  resources :sales do
    resources :payments
  end

  resources :payment_types

  resources :customers

  resources :dog_expenses

  resources :charges

  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
  end
  resources :users, :only =>[:index, :update, :new, :create, :edit, :destroy]

  resources :show_entries

  resources :dogs

  resources :shows

  get 'pregnancies_rpt' => 'reports#pregnancies'
  get 'dogs_rpt' => 'reports#dogs'
  get 'sales_rpt' => 'reports#sales'

  root 'home#index'

  

  
  match '*path(.:format)', :to => 'application#not_found', via: :all
end

app/models/pregnancy.rb
class Pregnancy < ActiveRecord::Base
  has_many :pictures, :as => :attachable, :dependent => :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true
  # belongs_to :attachable, polymorphic: true
  # mount_uploader :file, FileUploader

  belongs_to :dog
  has_many :matings
  has_many :litters

  validates :dog_id, presence: true
  validates :total_puppy, presence: true, numericality: true

  scope :expected, lambda{where('surgery_date >= ?', Date.today.to_s).order('surgery_date')}
  scope :already_due, lambda{where('surgery_date <= ?', Date.today.to_s).order('surgery_date desc')}

  def self.to_csv(options ={})
  	CSV.generate(options) do |csv|
  		csv << column_names
  		all.each do |item|
  			csv << item.attributes.values_at(*column_names)
  		end
  	end
  end
  
  def total_puppies
    litters.size
  end

  
  def self.set_value(data)
    pie_data=[]
    data.each do |key, value|
      pie_data << {:name => "#{key} - #{value}", :value=> value}
    end
  end
  
end

app/controllers/pregnancies_controller.rb
class PregnanciesController < ApplicationController
  before_action :set_pregnancy, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /pregnancies
  # GET /pregnancies.json
  def index
    @pregnancies = Pregnancy.order('heat_start_date, surgery_date')

    @plist = @pregnancies.already_due.order('due_date').map{|x| x.dog.call_name}.to_s.html_safe 
    @colors = [ [ "#8a10ae" ],[ "#f45a39" ],[ "#fa7083" ],[ "#b8ad3c" ],[ "#2babf2" ],[ "#1dae30" ],[ "#b6932d" ],[ "#e24436" ]]
    @puppy_count = Color.all.map{|c| ["#{c.name} - (#{c.litters.size})", c.litters.size]}.to_s.html_safe
    
   
    # @chart = LazyHighCharts::HighChart.new('graph') do |f|
    #   f.chart({:type => "column"})
    #   f.title(:text => "Pregnancies in 2003 as #{Date.today}")
    #   f.xAxis(:categories => @pregnancies.already_due.order('due_date').map{|x| x.dog.call_name})
      
    #   # f.tooltip(:formatter => "function() { return this.x +' '+ this.y + '<br>'+' Total:' + this.point.stackTotal;}".js_code)

    #   f.series(:name => "Puppies survive", :data => @pregnancies.already_due.order('due_date').map{|x| x.litters.where(survival: true).size})
    #   f.series(:name => "Puppies not survive", :data => @pregnancies.already_due.order('due_date').map{|x| x.litters.where(survival: false).size})
      
    #   f.plotOptions({column:{
    #     stacking: 'normal',
    #     # pointPadding: 0,
    #     groupPadding: 0, 
    #     dataLabels:{
    #       enabled: true,
    #       color: 'white'}
    #       }})

    #   f.yAxis( 
    #      title: { text: "Puppies", margin: 50},
    #      stackLabels: {
    #         style: {color: 'gray'},
    #         enabled: true}
    #     )

    #   f.series(:type => "pie", :name=> 'puppies', 
    #     :center=> [150, 80], :size=> 150, :showInLegend=> false,
    #     :data =>Color.all.map{|c| ["#{c.name} - (#{c.litters.size})", c.litters.size]},
    #     :colors => @colors)
    # end

    # @colors = Color.all.map{|c| ["##{rand(0xffffff).to_s(16)}"]}
    # @chart3 = LazyHighCharts::HighChart.new('pie') do |f|
    #   f.chart({:defaultSeriesType=>"pie" , :margin=> [50, 50, 50, 50]})
    #   series = {
    #     :type=> 'pie',
    #     :name=> 'Browser share',
    #     :data=> Color.all.map{|c| ["#{c.name} - (#{c.litters.size})", c.litters.size]},
    #     # :data => Pregnancy.set_value( Color.all.map{|c| [c.name, c.litters.size]} ),
    #     :colors => @colors,
    #     showInLegend: false
    #   }

    #   f.series(series)
    #   f.options[:title][:text] = "Puppies by colors"
    #   f.legend(:layout=> 'vertical',:width => 220,:borderWidth => 0, align: 'left', verticalAlign: 'middle') 
    #   f.plot_options(:pie=>{
    #     :allowPointSelect=>true, 
    #     :cursor=>"pointer" , 
    #     :dataLabels=>{
    #       :enabled=>true,
    #       :color=>"black"
    #     }
    #   })
    #  end

    # @chart1 = LazyHighCharts::HighChart.new('graph') do |f|
    #   f.title({ :text=>"Combination chart"})
    #   f.options[:xAxis][:categories] = ['Apples', 'Oranges', 'Pears', 'Bananas', 'Plums']
    #   f.labels(:items=>[:html=>"Total fruit consumption", :style=>{:left=>"40px", :top=>"8px", :color=>"black"} ]) 
    #   f.series(:type=> 'column',:name=> 'Jane',:data=> [3, 2, 1, 3, 4])
    #   f.series(:type=> 'column',:name=> 'John',:data=> [2, 3, 5, 7, 6])
    #   f.series(:type=> 'column', :name=> 'Joe',:data=> [4, 3, 3, 9, 0])
    #   f.series(:type=> 'column', :name=> 'Joe',:data=> [4, 3, 3, 9, 0])
    #   f.series(:type=> 'spline',:name=> 'Average', :data=> [3, 2.67, 3, 6.33, 3.33])
    #   f.series(:type=> 'pie',:name=> 'Total consumption', 
    #   :data=> [
    #     {:name=> 'Jane', :y=> 13, :color=> 'red'}, 
    #     {:name=> 'John', :y=> 23,:color=> 'green'},
    #     {:name=> 'Joe', :y=> 19,:color=> 'blue'}
    #   ],
    #   :center=> [100, 80], :size=> 100, :showInLegend=> false)
    # end  

    # @chart2 = LazyHighCharts::HighChart.new('graph') do |f|
    #   f.title(:text => "Population vs GDP For 5 Big Countries [2009]")
    #   f.xAxis(:categories => ["United States", "Japan", "China", "Germany", "France"])
    #   f.series(:name => "GDP in Billions", :yAxis => 0, :data => [14119, 5068, 4985, 3399, 2656])
    #   f.series(:name => "Population in Millions", :yAxis => 1, :data => [310,127,1340,81,65])

    #   f.yAxis [
    #     {:title => {:text => "GDP in Billions", :margin => 70}},
    #     {:title => {:text => "Population in Millions"}, :opposite => true},
    #   ]
    #   f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x  => -50, :layout => 'vertical',)
    #   f.chart({:defaultSeriesType => "column"})
    # end
    # @chart3 = LazyHighCharts::HighChart.new('pie') do |f|
    #   f.chart({:defaultSeriesType=>"pie" , :margin=> [50, 200, 60, 170]} )
    #   series = {
    #     :type=> 'pie',
    #     :name=> 'Browser share',
    #     :data=> [
    #       ['Firefox', 45.0],
    #       ['IE', 26.8],
    #      {
    #         :name=> 'Chrome', 
    #         :y=> 12.8,
    #         :sliced=> true,
    #         :selected=> true
    #      },
    #       ['Safari', 8.5],
    #       ['Opera', 6.2],
    #       ['Others', 0.7]
    #     ]
    #   }
    #   f.series(series)
    #   f.options[:title][:text] = "THA PIE"
    #   f.legend(:layout=> 'vertical',:style=> {:left=> 'auto', :bottom=> 'auto',:right=> '50px',:top=> '100px'}) 
    #   f.plot_options(:pie=>{
    #     :allowPointSelect=>true, 
    #     :cursor=>"pointer" , 
    #     :dataLabels=>{
    #       :enabled=>true,
    #       :color=>"black",
    #       :style=>{
    #         :font=>"13px Trebuchet MS, Verdana, sans-serif"
    #       }
    #     }
    #   })
    #  end

    # @chart4 = LazyHighCharts::HighChart.new('column') do |f|
    #   f.series(:name=>'John',:data=> [3, 20, 3, 5, 4, 10, 12 ])
    #   f.series(:name=>'Jane',:data=>[1, 3, 4, 3, 3, 5, 4,-46] ) 
    #   f.title({ :text=>"example test title from controller"})

    #   ### Options for Bar
    #   ### f.options[:chart][:defaultSeriesType] = "bar"
    #   ### f.plot_options({:series=>{:stacking=>"normal"}})

    #   ## or options for column
    #   f.options[:chart][:defaultSeriesType] = "column"
    #   f.plot_options({:column=>{:stacking=>"percent"}})
    #  end


    

    respond_to do |format|
      format.html
      format.csv {send_data @pregnancies.to_csv}
      format.xls #{send_data @pregnancies.to_csv(col_sep: "\t")}
    end
  end

  # GET /pregnancies/1
  # GET /pregnancies/1.json
  def show
  end

  # GET /pregnancies/new
  def new
    @pregnancy = Pregnancy.new
  end

  # GET /pregnancies/1/edit
  def edit
  end

  # POST /pregnancies
  # POST /pregnancies.json
  def create
    @pregnancy = Pregnancy.new(pregnancy_params)

    respond_to do |format|
      if @pregnancy.save
        format.html { redirect_to @pregnancy, notice: 'Pregnancy was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pregnancy }
      else
        format.html { render action: 'new' }
        format.json { render json: @pregnancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pregnancies/1
  # PATCH/PUT /pregnancies/1.json
  def update
    respond_to do |format|
      if @pregnancy.update(pregnancy_params)
        format.html { redirect_to @pregnancy, notice: 'Pregnancy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pregnancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pregnancies/1
  # DELETE /pregnancies/1.json
  def destroy
    @pregnancy.destroy
    respond_to do |format|
      format.html { redirect_to pregnancies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pregnancy
      @pregnancy = Pregnancy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pregnancy_params
      params.require(:pregnancy).permit(:name, :dog_id, :heat_start_date, :due_date, :surgery_date, :total_puppy, :note, :pictures_attributes => [:id, :file, '_destroy'])
    end
end

app/helpers/pregnancies_helper.rb
module PregnanciesHelper
end

app/views/pregnancies/_chart.html.erb
<script type="text/javascript" charset="utf-8">
$(function(){
  new Highcharts.Chart({
    chart: {
            renderTo: 'mychart', 
            type: 'column'
           },
    title: {text: ''},
    xAxis: {categories: <%= @plist %>},
    yAxis: {title: {text: "Puppies", margin: 50},
            stackLabels:{enabled: true, color: 'gray'}
    },
    // credits: {enabled: true, href: 'http://hungkwang.com', text: 'hungkwang.com'},
    credits: {enabled: false},
    plotOptions: {
              column:{
                stacking: 'normal',
                dataLabels:{ enbaled: true, color: 'white'}
              }
    },
    legend: {
           align: 'center', 
           labelFormatter: function(){
            return this.name;
           }
    },
    series: [
              {name: 'Puppies survive', data: <%= @pregnancies.already_due.order('due_date').map{|x| x.litters.where(survival: true).size} %>},
              {name: 'Puppies not survive', data: <%= @pregnancies.already_due.order('due_date').map{|x| x.litters.where(survival: false).size} %>},
              {type: 'pie',name: 'Puppies',
               center: [150,80],
               size: 150,
               showInLegend: false,
               colors: <%= @colors.to_s.html_safe %>,
               data: <%= @puppy_count %>
              }
            ]

  });
});
</script>

app/views/pregnancies/_data.html.erb
<tr <% if !Date.parse(pregnancy.surgery_date.to_s).past? %>class="due"<% else %>class="already"<% end %>>
  <td><%= link_to pregnancy.name, pregnancy %><br/><%= pregnancy.dog.call_name %></td>
  <!-- <td><%#= pregnancy.dog.call_name %></td> -->
  <td><%= pregnancy.heat_start_date %><br/><%= pregnancy.surgery_date %></td>
  <!-- <td><%#= pregnancy.due_date %></td> -->
  <!-- <td><%#= pregnancy.surgery_date %></td> -->
  <td><%= Date.parse(pregnancy.surgery_date.to_s).past? ? 'Due': time_ago_in_words(pregnancy.surgery_date) %><br/>
  <%= !Date.parse(pregnancy.surgery_date.to_s).past? ? '0': distance_of_time_in_words_to_now(pregnancy.surgery_date) %></td>
  <td><%= pregnancy.matings.first.sire.call_name  if !pregnancy.matings.first.nil? %></td>
  <td>
      <table class="table table-condensed">
        <% pregnancy.litters.order(:gender, :color_id).each do |p| %>
        <tr><td><%= p.gender %></td><td><%= p.color.name %></td><td><%= p.survival ? 'Yes': 'No' %></td><td><% if p.survival %><%= !p.dog_id.nil?  ? p.dog.status.name : 'Kennel' %><% else %> Deceased<% end %></td></tr>
        <% end %>
      </table>
  </td>
  <td style="width: 200px;"><pre><%= pregnancy.note %></pre></td>
  <td>
    <div class="btn-group">
      <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="icon-edit icon-white"></i>Actions
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to '<i class="icon-eye-open"></i> Show'.html_safe, pregnancy %></li>
        <li><%= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_pregnancy_path(pregnancy) %></li>
        <li class="divider"></li>
        <li><%= link_to '<i class="icon-trash"></i> Delete'.html_safe, pregnancy, method: :delete, data: {confirm: 'Are you sure?'} %></li>
      </ul>
    </div>
  </td>
</tr>

app/views/pregnancies/_theader.html.erb
               <tr>
                    <th>Name<br/>Dog</th>
                    <!-- <th>Dog</th> -->
                    <th>Heat date<br/>Surgery date</th>
                    <!-- <th>Estimate Due date</th> -->
                    <!-- <th>Estimate Surgery date</th> -->
                    <th>Due in/Age</th>
                    <th>Sire</th>
                    <th>Puppies</th>
                    <th>Note</th>
                    <th></th>
                    <th></th>
                    <th></th>
               </tr>

app/views/pregnancies/edit.html.erb
<div class="root">
	<div class="row">
		<div class="col-lg-12">
			<div class="grey-box">
				<h4>Editing pregnancy</h4>
					<%= render 'form' %>

					<div>
					<%= link_to 'Show', @pregnancy ,class: 'btn btn-primary' %> |
					<%= link_to 'Back', pregnancies_path,class: 'btn btn-primary'  %>
					</div>
			</div>
	 	</div>
	</div>
</div>

app/views/pregnancies/index.html.erb
<%= render :partial => 'chart' %>

<div class="root">
  <div class="row">
    <div class="col-lg-12">
      <div class="grey-box">
        
        <div class="page-header">
          <h4 class="page-header-text">Pregnancies</h4>
          <%= add_new_btn(new_pregnancy_path) %>
        </div>
        
        <div>
            <%#= high_chart("pregnancy", @chart) %>
            <%#= high_chart("chart1", @chart1) %>
            <%#= high_chart("chart2", @chart2) %>
            <%#= high_chart("chart3", @chart3) %>
            <%#= high_chart("chart4", @chart4) %>
            <div id="mychart"></div>
        </div>
<%#= @pregnancies.already_due.order('due_date').map{|x| x.litters.where(survival: true).size} %>
<%#= @pregnancies.already_due.order('due_date').map{|x| x.litters.where(survival: false).size} %>

        <div class="tabbable">
          <ul class="nav nav-pills">
            <li class="active">
              <a href="#pane1" data-toggle="tab">
              <span class="badge"><%= @pregnancies.size %></span>&nbsp;All Pregnancies</a>
            </li>
            <li>
                <a href="#pane2" data-toggle="tab">
                <span class="badge"><%= Pregnancy.expected.size %></span>&nbsp; Expected soon</a>
            </li>
            <li>
                <a href="#pane3" data-toggle="tab">
                <span class="badge"><%= Pregnancy.already_due.size %></span>&nbsp;Already Due</a>
            </li> 
          </ul>
          
          <div class="tab-content">
            <div id="pane1" class="tab-pane active">
              <% if @pregnancies.any? %>
                <div><span class="badge"><%= @pregnancies.size %></span> <%= 'pregnancy'.pluralize(@pregnancies.size) %> so far in year of <%= Date.today.year.to_s %>
                <span class="badge"><%= Pregnancy.expected.size %></span> expected soon
                <span style="float:right">
                  Download:
                  <%= link_to('<i class="icon-file"></i>CSV'.html_safe, pregnancies_path(format:"csv")) %> |
                  <%= link_to('<i class="icon-file"></i>Excel'.html_safe, pregnancies_path(format:"xls"))%>
                </span>
              </div>
              <% end %>

              <table class="table table-condensed table-striped">
                <thead>
                  <%= render :partial => 'theader' %>
                </thead>
                <tbody>
                  <% @pregnancies.each do |pregnancy| %>
                    <%= render :partial => 'data', locals: {pregnancy: pregnancy} %>
                  <% end %>
                  <tr><td colspan="7">&nbsp;</td><td><%= Litter.count%></td></tr>
                </tbody>
              </table>

              <br>
              <%= link_to 'New Pregnancy', new_pregnancy_path %>
            </div>

            <div id="pane2" class="tab-pane">
              <table class="table table-striped">
                <thead>
                  <%= render :partial => 'theader' %>
                </thead>
                <tbody>
                  <% Pregnancy.expected.each do |pregnancy| %>
                    <%= render :partial => 'data', locals: {pregnancy: pregnancy} %>
                  <% end %>
                </tbody>
              </table>
            </div>
            
            <div id="pane3" class="tab-pane">
              <table class="table table-striped">
                <thead>
                  <%= render :partial => 'theader' %>
                </thead>
                <tbody>
                  <% Pregnancy.already_due.each do |pregnancy| %>
                    <%= render :partial => 'data', locals: {pregnancy: pregnancy} %>
                  <% end %>
                </tbody>
              </table>
            </div>
            </div>

          </div><!-- ./tab-content -->
        </div><!-- ./tabbable -->



        
      </div>
    </div>
  </div>
</div>

app/views/pregnancies/index.xls.erb
<table class="table table-striped">
<thead>
  <tr>
    <th>Name</th>
    <th>Pregnant Dog</th>
    <th>Heat start date</th>
    <th>Estimate Due date</th>
    <th>Estimate Surgery date</th>
    <th>Due in</th>
    <th>Puppy</th>
  </tr>
</thead>

<tbody>
  <% @pregnancies.each do |pregnancy| %>
    <tr>
      <td><%= link_to pregnancy.name, pregnancy %></td>
      <td><%= pregnancy.dog.call_name %></td>
      <td><%= pregnancy.heat_start_date %></td>
      <td><%= pregnancy.due_date %></td>
      <td><%= pregnancy.surgery_date %></td>
      <td><%= Date.parse(pregnancy.surgery_date.to_s).past? ? 'Due': time_ago_in_words(pregnancy.surgery_date) %></td>
      <td><%= pregnancy.total_puppy %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/pregnancies/new.html.erb
<div class="root">
	<div class="row">
		<div class="col-lg-12">
			<div class="grey-box">
				<h4>New pregnancy</h4>

				<%= render 'form' %>

				<%= link_to 'Back', pregnancies_path ,class: 'btn btn-primary' %>
			</div>
	 	</div>
	</div>
</div>

app/views/pregnancies/show.html.erb
<div class="root">
  <div class="row">
    <div class="col-lg-12">
      <div class="grey-box">
        <p id="notice"><%= notice %></p>
        <h4>Pregnancy Detail</h4>

        <div class="col-md-4">
          <div class="tabbable">
          <ul class="nav nav-pills">
            <li class="active"><a href="#pane1" data-toggle="tab">Pregnancy Information</a></li>
          </ul>
          </div>
              <p>
                <strong>Name:</strong>
                <%= @pregnancy.name %>
              </p>
              <p>
                <strong>Bitch:</strong>
                <%= @pregnancy.dog.name %>
              </p>
              <p>
                <strong>Color:</strong>
                <%= @pregnancy.dog.color.name %>
              </p>
              <p>
                <strong>Heat start date:</strong>
                <%= @pregnancy.heat_start_date %>
              </p>
              <p>
                <strong>Estimate Due date:</strong>
                <%= @pregnancy.due_date %>
              </p>
              <p>
                <strong>Estimate Surgery date:</strong>
                <%= @pregnancy.surgery_date %>
              </p>
              <p>
                <strong>Note:</strong>
                <%= @pregnancy.note %>
              </p>
              <p>
                <strong>Total puppy:</strong>
                <%= @pregnancy.total_puppies %>
              </p>
              <p>
                <strong>Puppies Age:</strong>
                <%= time_ago_in_words(@pregnancy.surgery_date) %>
              </p>
              <%= link_to 'Edit', edit_pregnancy_path(@pregnancy),class: 'btn btn-primary'  %> |
              <%= link_to 'Back', pregnancies_path,class: 'btn btn-primary'  %>
        </div>
        <div class="col-md-4">
          <div class="tabbable">
            <ul class="nav nav-pills">
              <li class="active">
                <a href="#pane1" data-toggle="tab"><span class="badge pull-right"><%= @pregnancy.matings.size %></span>Matting Information&nbsp;</a>
              </li>
            </ul>
          </div>
          <p><strong>Heat start date:</strong><%= @pregnancy.heat_start_date %></p>
          <p>
            <strong>Dog:</strong> <%= @pregnancy.matings.first.sire.call_name  if !@pregnancy.matings.first.nil? %>
            <strong>Color:</strong> <%= @pregnancy.matings.first.sire.color.name if !@pregnancy.matings.first.nil?%>
          </p>
            <table class="table table-striped">
              <tr>
                <td>Dog</td>
                <td>Progesterone</td>
                <td>Mating Date</td>
                <td>Days</td>
                <td></td>
              </tr>
              <% @pregnancy.matings.order('mating_date DESC').each do |mating| %>
                <tr>
                  <td><%= mating.sire.call_name %></td>
                  <td><%= mating.progesterone %> ml</td>
                  <td><%= mating.mating_date %></td><td><%=  distance_of_time_in_words(mating.mating_date, @pregnancy.heat_start_date)%></td>
                  <td>
                    <%#= link_to "Edit", edit_pregnancy_mating_path(@pregnancy, mating), :class => "btn"%>
                    <%= link_to "Edit", edit_pregnancy_mating_path(@pregnancy, mating), :class => "btn btn-mini", :remote => true, "data-toggle" => "modal", "data-target" => "my-modal"%>
                  </td>
                </tr>
              <% end %>
            </table>
            
            <div>
            <a href="javascript:void(0)" onclick="javascript:$('.panel').slideToggle('slow')" class="btn btn-primary">Add Mating</a>
            </div>
            <div class="panel">
              <h4>Add Mating Record</h4>
              <%= render 'matings/matingForm' %>
            </div>

        </div>
        <div class="col-md-4">
          <div class="tabbable">
            <ul class="nav nav-pills">
              <li class="active">
                <a href="#pane1" data-toggle="tab"><span class="badge pull-right"><%= @pregnancy.litters.size %></span>Litter Information&nbsp;</a>
              </li>
            </ul>
          </div>
           <p><strong>Litter Information</strong></p>
           <p><%= @pregnancy.litters.where(gender: 'Male').size %> M - <%= @pregnancy.litters.where(gender: 'Female').size %> F</p>
            <table class="table table-striped">
              <tr><td>Gender</td><td>Color</td><td>Survival</td><td>Dog</td><td></td></tr>
              <% @pregnancy.litters.each do |litter| %>
                <tr>
                  <td><%= litter.gender %></td>
                  <td><%= litter.color.name %></td>
                  <td><%= yesno(litter.survival) %></td> 
                  <td><%= litter.dog.call_name if !litter.dog.nil?%></td>
                  <td>
                    <%#= link_to "Edit", edit_pregnancy_litter_path(@pregnancy, litter) %>
                    <%= link_to "Edit", edit_pregnancy_litter_path(@pregnancy, litter), :class => "btn btn-mini", :remote => true, "data-toggle" => "modal", "data-target" => "my-modal"%>
                  </td> 
                </tr>
              <% end %>
            </table>

            <div>
              <a href="javascript:void(0)" onclick="javascript:$('.litter-panel').slideToggle('slow')" class="btn btn-primary">Add Litter</a>
            </div>
            <div class="litter-panel">             
              <h4>Add Litter</h4>
              <%= render 'litters/litterForm' %>
            </div>    
        </div>

        <div style="clear: both;"></div>
        
        <div class="row">
          <% @pregnancy.pictures.each do |pic| %>
            <div class="col-md-3">
                <%= image_tag(pic.file.url, :class => "small-image") %>
            </div>
          <% end %>
        </div>


        <!-- Modal -->
        <div class="modal fade" id="my-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
              </div>
              <div class="modal-body">
                ...
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->


           



      </div>
    </div>
  </div>
</div>