config/routes.rb
Showtrac::Application.routes.draw do
  
  
  resources :services

  resources :statuses

  resources :pregnancies do
    resources :matings
    resources :litters
  end

  resources :colors

  resources :photos

  resources :payment_statuses

  resources :sales do
    resources :payments
  end

  resources :payment_types

  resources :customers

  resources :dog_expenses

  resources :charges

  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
  end
  resources :users, :only =>[:index, :update, :new, :create, :edit, :destroy]

  resources :show_entries

  resources :dogs

  resources :shows

  get 'pregnancies_rpt' => 'reports#pregnancies'
  get 'dogs_rpt' => 'reports#dogs'
  get 'sales_rpt' => 'reports#sales'

  root 'home#index'

  

  
  match '*path(.:format)', :to => 'application#not_found', via: :all
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    # if user.admin?
    #     can :manage, :all
    # else
    #     can :read, :all
    # end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    if user.has_role? :admin
        can :manage, :all
    else
        can :read, :all
    end
  end
end

app/models/charge.rb
class Charge < ActiveRecord::Base
	has_many :dog_expenses

	validates :name, :description, presence:true
end

app/models/color.rb
class Color < ActiveRecord::Base
	has_many :dogs
	has_many :litters
	validates :name, presence: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :sales

	has_many :pictures, :as => :attachable, :dependent => :destroy
	accepts_nested_attributes_for :pictures, :allow_destroy => true

	validates :name, :first_name, :last_name, :email, :phone, :mobile, presence:true
end

app/models/dog.rb
class Dog < ActiveRecord::Base
	GENDER_TYPE = %w[Female Male]
	has_many :show_entries
	has_many :dog_expenses
	has_many :sales
	has_many :photos
	has_many :pregnancies
	belongs_to :color
	belongs_to :status
	
	belongs_to :sire, class_name: "Dog", foreign_key: "sire_id"
	belongs_to :dams, class_name: "Dog", foreign_key: "dams_id"

	has_many :pictures, :as => :attachable, :dependent => :destroy
	accepts_nested_attributes_for :pictures, :allow_destroy => true

	validates :name, :call_name, :color_id, presence:true

	scope :bitches, lambda{where(gender: 'Female', status_id: 1)}
	scope :dogs, lambda{where(gender: 'Male', status_id: 1)}
	scope :sold, lambda{joins(:sales).where(sales: {service_id: 1})}
	def self.to_csv(options ={})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end

end

app/models/dog_expense.rb
class DogExpense < ActiveRecord::Base
  belongs_to :dog
  belongs_to :charge
  # belongs_to :show
  belongs_to :show_entry

  validates :dog_id, :charge_id, presence:true
  validates :amount, presence: true, numericality: true
  
  # scope :tw_dollars, -> {where(currency: 'TW')}
  scope :tw_dollars, lambda{where(currency: 'TW')}
  scope :us_dollars, lambda{where(currency: 'USD')}

	def self.to_csv(options ={})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |dog_expense|
				csv << dog_expense.attributes.values_at(*column_names)
			end
		end
	end
end

app/models/litter.rb
class Litter < ActiveRecord::Base
  belongs_to :pregnancy
  belongs_to :color
  belongs_to :dog

  validates :pregnancy_id, :gender, :color_id, presence: true

  def self.survial_count(pregnancy)
  	pregnancy.where(survival: true).size
  end

  def self.count_gender(pregnancy)
  	# where(gender: gender, pregnancy_id: p).size
  	# where(pregnancy_id: pregnancy).count(group: :gender)
  	# where(pregnancy_id: pregnancy).group("gender").count
  	where(pregnancy_id: pregnancy).group(:gender, :survival).size
  end
end

app/models/mating.rb
class Mating < ActiveRecord::Base
  belongs_to :pregnancy
  belongs_to :sire, class_name: "Dog", foreign_key: "sire_id"

  validates :pregnancy_id, :sire_id, presence: true
  
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :sale
	belongs_to :payment_status
	belongs_to :payment_type

	validates :sale_id, :payment_type_id, :payment_status_id, presence: true
	validates :amount, presence: true, numericality: true	
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :attachable, polymorphic: true
  mount_uploader :file, FileUploader
end

app/models/pregnancy.rb
class Pregnancy < ActiveRecord::Base
  has_many :pictures, :as => :attachable, :dependent => :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true
  # belongs_to :attachable, polymorphic: true
  # mount_uploader :file, FileUploader

  belongs_to :dog
  has_many :matings
  has_many :litters

  validates :dog_id, presence: true
  validates :total_puppy, presence: true, numericality: true

  scope :expected, lambda{where('surgery_date >= ?', Date.today.to_s).order('surgery_date')}
  scope :already_due, lambda{where('surgery_date <= ?', Date.today.to_s).order('surgery_date desc')}

  def self.to_csv(options ={})
  	CSV.generate(options) do |csv|
  		csv << column_names
  		all.each do |item|
  			csv << item.attributes.values_at(*column_names)
  		end
  	end
  end
  
  def total_puppies
    litters.size
  end

  
  def self.set_value(data)
    pie_data=[]
    data.each do |key, value|
      pie_data << {:name => "#{key} - #{value}", :value=> value}
    end
  end
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :dog
  belongs_to :customer
  belongs_to :service
  has_many :payments, :dependent => :destroy

  validates :dog_id, :customer_id, presence: true
  validates :sale_price, presence: true, numericality: true


    def self.to_csv(options ={})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end
end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :sales	
end

app/models/show.rb
class Show < ActiveRecord::Base
	has_many :show_entries
	# has_many :dog_expenses

	validates :name, :kennel_club, presence: true

	def self.to_csv(options ={})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end
end

app/models/show_entry.rb
class ShowEntry < ActiveRecord::Base
  belongs_to :dog
  belongs_to :show
  has_many :dog_expenses

  has_many :pictures, :as => :attachable, :dependent => :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true
  
  validates :dog_id, :show_id, presence: true
  validates :points, numericality: { only_integer: true}
  validates :entry_fee, numericality:  true
  validates :handling_fee, numericality: true


  	def self.to_csv(options ={})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end
end

app/models/status.rb
class Status < ActiveRecord::Base
	has_many :dogs
end

app/models/user.rb
class User < ActiveRecord::Base
    rolify
    # Include default devise modules. Others available are:
    # :token_authenticatable, :confirmable,
    # :lockable, :timeoutable and :omniauthable
    # devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

    # after_create :assign_user_role

    validate :display_name,:email, presence: true, uniqueness: true

    def avatar
      Gravatar.new(self.email).image_url
    end

    def admin?
        has_role?(:admin)
    end

    def user?
        has_role?(:user) || admin?
    end

    private

    # def assign_user_role
    #     self.add_role :user
    # end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/shared/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" data-no-turbolink='true'>Kennel MGT</a>
    </div>

    <div class="navbar-collapse collapse">
		<ul class="nav navbar-nav">
			<% if current_user && current_user.admin? %>
        		<li class="<%= 'active' if controller_name == 'pregnancies' %>"><a href="<%= "#{pregnancies_path}" %>" data-no-turbolink='true'>Pregnancies</a></li>
	        	<li class="<%= 'active' if controller_name == 'dog_expenses' %>"><a href="<%= "#{dog_expenses_path}" %>" data-no-turbolink='true'>Expenses</a></li>
				<li class="<%= 'active' if controller_name == 'dogs' %>"><a href="<%= "#{dogs_path}" %>" data-no-turbolink='true'>Dogs</a></li>
	        	<li class="dropdown">
	              	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Management <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><%= link_to "Sales", sales_path %></li>
          				<li><%= link_to "Shows", shows_path %></li>
          				<li><%= link_to "Shows Entries", show_entries_path %></li>
						<li><%= link_to "Customers", customers_path %></li>
						<!-- 
						<li><a href="<%#= "#{matings_path}" %>">Matings</a></li>
						<li><a href="<%#= "#{litters_path}" %>">Litters</a></li>
						 -->
						<li><%= link_to "Charges", charges_path %></li>
						<li><%= link_to "Payment Types", payment_types_path %></li>
						<li><%= link_to "Payment Status", payment_statuses_path %></li>
						<li><%= link_to "Colors", colors_path %></li>
						<li><%= link_to "Statuses", statuses_path %></li>
						<li><%= link_to "Services", services_path %></li>
						<li><%= link_to "Users", users_path %></li>
					</ul>
		          </li>
        	<% end %>
		</ul>
		<ul class="nav pull-right">
	      <% if current_user %>  
	          <li class="dropdown">
	            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="<%= current_user.avatar%>" class="avatar"></img> <%= current_user.display_name.titleize %><b class="caret"></b></a>
	            <ul class="dropdown-menu">
	              <li><%= link_to 'My Dashboard', "" %></li>
	              <li><%= link_to 'Sign out', destroy_user_session_url(), :method => :delete %></li>  
	              <li><%#= link_to "Profile", edit_user_registration_path(current_user) %></li>
	            </ul>
	          </li>
	      <% else %>
	          <li><%#= link_to 'Sign up', new_user_registration_url() %></li>
	          <li><%= link_to 'Sign in', new_user_session_url() %></li>
	      <% end %>
	    </ul>
		<% if current_user %>
			<div class="nav pull-right">
				<!-- 
				<%= form_tag "", :id=> "search-form", :class => "navbar-search pull-right", :method => :get do %>
				<%= text_field_tag :search, nil, :class => "search-query", :placeholder => "Search..." %>
				<% end %>
				-->
			</div>
		<% end %>  
	    <!-- 
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" placeholder="Email" class="form-control">
        </div>
        <div class="form-group">
          <input type="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
      </form> -->
    </div><!--/.navbar-collapse -->

  </div>
</div>