config/routes.rb
Showtrac::Application.routes.draw do
  
  
  resources :services

  resources :statuses

  resources :pregnancies do
    resources :matings
    resources :litters
  end

  resources :colors

  resources :photos

  resources :payment_statuses

  resources :sales do
    resources :payments
  end

  resources :payment_types

  resources :customers

  resources :dog_expenses

  resources :charges

  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
  end
  resources :users, :only =>[:index, :update, :new, :create, :edit, :destroy]

  resources :show_entries

  resources :dogs

  resources :shows

  get 'pregnancies_rpt' => 'reports#pregnancies'
  get 'dogs_rpt' => 'reports#dogs'
  get 'sales_rpt' => 'reports#sales'

  root 'home#index'

  

  
  match '*path(.:format)', :to => 'application#not_found', via: :all
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :dog
  belongs_to :customer
  belongs_to :service
  has_many :payments, :dependent => :destroy

  validates :dog_id, :customer_id, presence: true
  validates :sale_price, presence: true, numericality: true


    def self.to_csv(options ={})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.order(sale_date: :desc)
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:dog_id, :customer_id, :sale_date, :sale_price, :note, :currency, :service_id)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale, :html=>{:class => 'form-horizontal', :role=> 'form'}) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h4>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-xs-4">
      <%= f.label :dog %>
      <%= f.select(:dog_id, Dog.all.map{|d|[d.name, d.id]}, {include_blank:'Select a Dog'}, {class: 'form-control'}) %>  
    </div>
  </div>

  <div class="form-group">
    <div class="col-xs-4">
      <%= f.label :service_id %>
      <%= f.select(:service_id, Service.all.map{|d|[d.name, d.id]}, {include_blank:'Select a Service'}, {class: 'form-control'}) %>  
    </div>
  </div>
  <div class="form-group">
    <div class="col-xs-4">
      <%= f.label :customer %>
      <%= f.select(:customer_id, Customer.all.map{|c| [c.name, c.id]}, {include_blank:'Select a Customer'}, {class: 'form-control'}) %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-xs-4">
      <%= f.label :sale_date %>
      <%#= f.date_select :sale_date %>
      <div class="input-append date" id="dp3" data-date-format="yyyy-mm-dd">
        <%= f.text_field :sale_date, value: date_value(@sale.sale_date), :readonly => true, class: 'form-control' %><span class="add-on"><i class="icon-th"></i></span>
      </div>
    </div>
  </div>
      
  <div class="form-group">
    <div class="col-xs-4">
      <%= f.label :currency %>
      <%= f.select(:currency, $CURRENCIES.map{|c| [c,c]},{},{class: 'form-control'})%>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-xs-4">
      <%= f.label :sale_price %>
      <%= f.text_field :sale_price, class: 'form-control' %>
    </div>
  </div>    
  
  <div class="form-group">
    <div class="col-xs-4">
      <%= f.label :note %>
      <%= f.text_area :note , id: 'message_area', class: 'form-control' %>
    </div>
  </div>      
  
  <br/>
  <p><%= f.submit class: 'btn btn-primary' %></p>
  
<% end %>

app/views/sales/edit.html.erb
<div class="root">
	<div class="row">
		<div class="col-lg-12">
			<div class="grey-box">
				<h4>Editing sale</h4>

				<%= render 'form' %>

				<%= link_to 'Show', @sale, class: 'btn btn-primary' %> |
				<%= link_to 'Back', sales_path, class: 'btn btn-primary' %>
			</div>
	 	</div>
	</div>
</div>

app/views/sales/index.html.erb
<div class="root">
  <div class="row">
    <div class="col-lg-12">
        <div class="grey-box">
        <div class="page-header">
          <h4 class="page-header-text">Sales</h4>
          <%= add_new_btn(new_sale_path) %>
        </div>
        <table class="table table-condensed table-striped">
          <thead>
            <tr>
              <th>Dog</th>
              <th>Customer</th>
              <th>Sale date</th>
              <th>Sale price</th>
              <th>Service</th>
              <th>Note</th>
              <th>Photo</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @sales.each do |sale| %>
              <tr>
                <td><%= link_to sale.dog.call_name, dog_path(sale.dog.id) %></td>
                <td><%= link_to(sale.customer.name, customer_path(sale.customer.id) )%></td>
                <td><%= sale.sale_date %></td>
                <td><%= currency_to(sale.sale_price,sale.currency) %></td>
                <td><%= sale.service.name %></td>
                <td style="width: 250px;"><pre><%= sale.note %></pre></td>
                <td><%= sale.dog.pictures.size %></td>
                <td>
                  <div class="btn-group">
                    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                      <i class="icon-edit icon-white"></i>Actions
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to '<i class="icon-eye-open"></i> Show'.html_safe, sale%></li>
                      <li><%= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_sale_path(sale) %></li>
                      <li class="divider"></li>
                      <li><%= link_to '<i class="icon-trash"></i> Delete'.html_safe, sale, method: :delete, data: {confirm: 'Are you sure(this action will also delete assoicated payments ) ?'} %></li>
                    </ul>
                  </div>
                </td>
                <!-- 
                <td><%= link_to 'Show', sale %></td>
                <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
                <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure(this action will also delete assoicated payments ) ?' } %></td>
                 -->
              </tr>
            <% end %>
            <tr><td colspan="3" align="right">Total</td><td><%= currency_to(Sale.sum(:sale_price),'TW') %></td><td colspan="3">&nbsp;</td></tr>
          </tbody>
        </table>

        <br>

        <%= link_to 'New Sale', new_sale_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/sales/new.html.erb
<div class="root">
	<div class="row">
		<div class="col-lg-12">
			<div class="grey-box">
			<h4>New sale</h4>

			<%= render 'form' %>

			<%= link_to 'Back', sales_path,class: 'btn btn-primary'  %>
			</div>
	 	</div>
	</div>
</div>

app/views/sales/show.html.erb
<div class="root">
  <div class="row">
    <div class="col-lg-12">
      <div class="grey-box">
      <p id="notice"><%= notice %></p>
        <h4>Sale Details</h4>

      <% @sale.dog.pictures.each do |pic| %>
        <%= image_tag(pic.file.url, heigh: 200, width: 200) %>
      <% end %>
      
      <p>
        <strong>Dog:</strong>
        <%= @sale.dog.name %>
      </p>

      <p>
        <strong>Service:</strong>
        <%= @sale.service.name %>
      </p>
      
      <p>
        <strong>Customer:</strong>
        <%= @sale.customer.name %>
      </p>

      <p>
        <strong>Sale date:</strong>
        <%= @sale.sale_date %>
      </p>

      <p>
        <strong>Sale price:</strong>
        <%= currency_to(@sale.sale_price, @sale.currency) %>
      </p>

      <p>
        <strong>Note:</strong>
        <%= @sale.note %>
      </p>

      <p>
        <strong>Payment(s):</strong>
        <table class="table table-strped">
        <% @sale.payments.order("payment_date").each do |pay| %>
          <tr>
            <td><%= pay.payment_date %></td>
            <td><%= pay.payment_type.name %></td>
            <td><%= currency_to(pay.amount, pay.currency) %></td>
            <td><%= pay.payment_status.name %></td>
            <td><%= pay.note %></td>
            <td><%= link_to "Edit", edit_sale_payment_path(@sale,pay) %> | Destroy</td>
          </tr>
        <% end %>
        </table>
      </p>

      <a href="javascript:void(0)" onclick="javascript:$('.panel').slideToggle('slow')" class="btn btn-primary">Add Payment</a>

      <div class="panel">
        <h4>Add Payment</h4>
        <%= render 'payments/paymentForm' %>
      </div>

      <%= link_to 'Edit', edit_sale_path(@sale), class: 'btn btn-primary' %>
      <%= link_to 'Back', sales_path,class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>