config/routes.rb
Showtrac::Application.routes.draw do
  
  
  resources :services

  resources :statuses

  resources :pregnancies do
    resources :matings
    resources :litters
  end

  resources :colors

  resources :photos

  resources :payment_statuses

  resources :sales do
    resources :payments
  end

  resources :payment_types

  resources :customers

  resources :dog_expenses

  resources :charges

  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
  end
  resources :users, :only =>[:index, :update, :new, :create, :edit, :destroy]

  resources :show_entries

  resources :dogs

  resources :shows

  get 'pregnancies_rpt' => 'reports#pregnancies'
  get 'dogs_rpt' => 'reports#dogs'
  get 'sales_rpt' => 'reports#sales'

  root 'home#index'

  

  
  match '*path(.:format)', :to => 'application#not_found', via: :all
end

app/models/charge.rb
class Charge < ActiveRecord::Base
	has_many :dog_expenses

	validates :name, :description, presence:true
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @charge }
      else
        format.html { render action: 'new' }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.require(:charge).permit(:name, :description)
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
<%= form_for(@charge, :html => {:class=>'form-horizontal', :role => 'form'}) do |f| %>
  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h4>

      <ul>
      <% @charge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-group">
    <div class="col-xs-4">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
    
  <div class="form-group">
    <div class="col-xs-4">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
  
  
  <br/>
  <p><%= f.submit class: 'btn btn-primary' %></p>
  
<% end %>

app/views/charges/edit.html.erb
<div class="root">
	<div class="row">
		<div class="col-lg-12">
			<div class="grey-box">
			<h4>Editing charge</h4>

			<%= render 'form' %>

			<%= link_to 'Show', @charge ,class: 'btn btn-primary' %> |
			<%= link_to 'Back', charges_path, class: 'btn btn-primary'  %>
			</div>
	 	</div>
	</div>
</div>

app/views/charges/index.html.erb
<div class="root">
  <div class="row">
      <div class="col-lg-12">
          <div class="grey-box">
            <div class="page-header">
              <h4 class="page-header-text">Charges</h4>
              <%= add_new_btn(new_charge_path) %>
            </div>
            
            <table class="table table-condensed table-striped">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th></th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>

              <tbody>
                <% @charges.each do |charge| %>
                  <tr>
                    <td><%= charge.name %></td>
                    <td><%= charge.description %></td>
                    <td>
                        <%= link_to 'Show', charge, class: 'btn btn-primary btn-small' %>
                        <%= link_to 'Edit', edit_charge_path(charge), class: 'btn btn-primary btn-small' %>
                        <%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-small' %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

            <br>

            <%= link_to 'New Charge', new_charge_path %>
        </div>      
      </div>
  </div>
</div>

app/views/charges/new.html.erb
<div class="root">
	<div class="row">
		<div class="col-lg-12">
			<div class="grey-box">
				<h4>New charge</h4>

				<%= render 'form' %>

				<%= link_to 'Back', charges_path, class: 'btn btn-primary'  %>
			</div>
	 	</div>
	</div>
</div>

app/views/charges/show.html.erb
<div class="root">
  <div class="row">
    <div class="col-lg-12">
      <div class="grey-box">
		<p id="notice"><%= notice %></p>

		<p>
		  <strong>Name:</strong>
		  <%= @charge.name %>
		</p>

		<p>
		  <strong>Description:</strong>
		  <%= @charge.description %>
		</p>

		<%= link_to 'Edit', edit_charge_path(@charge) , class: 'btn btn-primary' %> |
		<%= link_to 'Back', charges_path,class: 'btn btn-primary'  %>
      </div>
    </div>
  </div>
</div>